spring.application.name=bct-godfather

discord.bot.token=${DISCORD_BOT_TOKEN}
server.port=8080
cohere.api.key=${COHERE_API_KEY}
mangadex.base-url=https://api.mangadex.org

cover.template.path=classpath:covers/Cover_template.docx
cover.csv.path=classpath:covers/BCT081_students_data.csv