spring.application.name=bct-godfather

discord.bot.token=${DISCORD_BOT_TOKEN}
server.port=8080
cohere.api.key=${COHERE_API_KEY}
mangadex.base-url=https://api.mangadex.org

reminder.channel.id=1514522483787694210
spring.jpa.hibernate.ddl-auto=update

cover.template.path=classpath:covers/Cover_template.docx
cover.csv.path=classpath:covers/BCT081_students_data.csv
## postgres
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true